{% set name = "eidos" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  path: .

build:
  noarch: python
  number: 0
  script: $PYTHON -m pip install .

requirements:
  build:
    - pip
    - numpy>=1.17
    - scipy
    - astropy
    - future
  host:
    - python
  run:
    - python
    - numpy>=1.17
    - scipy
    - astropy
    - future

test:
  imports:
    - eidos

about:
  home: https://github.com/i4Ds/eidos.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'edios - Primary beam modelling of radio astronomy antennas.'
  description: |
    Primary beam modelling of radio astronomy antennas.
  doc_url: https://github.com/i4Ds/eidos.git
  dev_url: https://github.com/i4Ds/eidos.git

extra:
  recipe-maintainers:
    - Christoph Vögele
